apiVersion: v1
kind: Service
metadata:
  name: fastify-app-svc
  labels:
    run: fastify
spec:
  selector:
    app: fastify
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
